####
# This Dockerfile is used in order to build a container that runs the Quarkus application in native (no JVM) mode.
#
# Before building the container image run:
#
# ./mvnw package -Pnative
#
# Then, build the image with:
#
# docker build -f src/main/docker/Dockerfile.native -t quarkus/poc-quarkus .
#
# Then run the container using:
#
# docker run -i --rm -p 8080:8080 quarkus/poc-quarkus
# docker build -f docker/Dockerfile.native -t quarkus/poc-quarkus-native:native-aarch64 .
# docker run --rm -p 8080:8080 quarkus/poc-quarkus-native:local
###
FROM registry.access.redhat.com/ubi8/ubi-minimal:8.5@sha256:3f32ebba0cbf3849a48372d4fc3a4ce70816f248d39eb50da7ea5f15c7f9d120
WORKDIR /work/
RUN chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work
COPY --chown=1001:root target/*-runner /work/application

EXPOSE 8080
USER 1001

CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]
RUN true


