####
# This Dockerfile is used in order to build a container that runs the Quarkus application in native (no JVM) mode.
#
# Before building the container image run:
#
# ./mvnw package -Pnative
#
# Then, build the image with:
#
# docker build -f src/main/docker/Dockerfile.native -t quarkus/poc-quarkus .
#
# Then run the container using:
#
# docker run -i --rm -p 8080:8080 quarkus/poc-quarkus
# docker build -f src/main/docker/Dockerfile.native -t quarkus/poc-quarkus-native:native-aarch64 .
# docker run --rm -p 8080:8080 quarkus/poc-quarkus-native:local
###
FROM ghcr.io/graalvm/graalvm-ce:ol7-java11-22.3.0-b2@sha256:49d1383ee58d48a8268ad5db80bd329687155811e9ff9f1af5047756e4a20f71
WORKDIR /work/
RUN chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work
COPY --chown=1001:root target/*-runner /work/application

EXPOSE 8080
USER 1001

CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]


